### ISSUE TITLE
Error while trying to run then demo application in my localhost

### ISSUE THREAD

**Issue by pmaingi** [openMF/community-app#1295]
Hi guys,
Am trying to run this demo application in my laptop. I followed all the steps but the below step shows this error.

6.To preview the app, run the following command on the project root folder

grunt serve

Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\WORK\community-app\node_modules\grunt\lib\grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Could i be skipping something as am new to nodejs ?

**Comment by vishwasbabu** [comment]
http://stackoverflow.com/questions/23622179/grunt-cannot-find-module-coffee-script

**Comment by pmaingi** [comment]
Thanks @vishwasbabu.
